server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernat:
        show_sql: true
        format_Sql: true

security:
  oauth2:
    sso:
      login-path: /mylogin        
