server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernat:
        show_sql: true
        format_Sql: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin    
